[directory]
truncation_length = 5

[cmd_duration]
min_time = 1000
prefix = "time "

[memory_usage]
show_percentage = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 20
style = "bold red"

[git_branch]
truncation_length = 15

[kubernetes]
disabled = false

